### ISSUE TITLE
Failure w/ Qt 5.2.1 on Ubuntu 14.04 Trusty

### ISSUE THREAD

**Issue by rakhimov** [woboq/verdigris#10]
Using ``W_SIGNAL`` macro with gcc 7 and qt 5.2.1 on Trusty:
```
.../verdigris/wobjectimpl.h:255:48:error: ‘IsQEnumHelper’ is not a member of ‘QtPrivate’
         constexpr uint moreFlags = (QtPrivate::IsQEnumHelper<typename Prop::PropertyType>::Value

```
Build: https://travis-ci.org/rakhimov/scram/jobs/325736256

**Comment by ogoffart** [comment]
Qt 5.2 Is quite old.  IsQEnumHelper was introduced in Qt 5.5
I wonder if we should #ifdef this part (adding the flag that a type is a Q_ENUM does not make sens with older Qt anyway), or simply say that we only support Qt 5.6

**Comment by rakhimov** [comment]
Indeed, it works w/ Qt 5.5 on Ubuntu 16.04 Xenial.
I only tested W_SIGNAL and W_OBJECT.

**Comment by ogoffart** [comment]
Note that the test were also imported from Qt 5.6 and tests stuff that are not supposed to work with earlier versions. 
For example, Q_GADGET did not allow to have invokable before Qt 5.5 and so the W_GADGET macro won't compile.  
So if we want the test to pass with older qt, we would need to #ifdef a lot of code.

I think that it is safe to assume that Qt 5.5 should be a recent enough requirement.
