### ISSUE TITLE
CI builds

### ISSUE THREAD

**Issue by rakhimov** [woboq/verdigris#11]
Thank you for the code!

I'd like to replace Qt MOC with Verdigris to use C++17 features without *fear*.
It would be very much assuring if Verdigris had CI
for versions of gcc, clang, qt5 on major platforms (Ubuntu, macOS, Windows, msys2/mingw64).

**Comment by ogoffart** [comment]
I guess I could try to setup travis.

**Comment by ogoffart** [comment]
Thanks for the travis build script.
I now even added a travis image in the README: https://github.com/woboq/verdigris
And the build is passing
