### ISSUE TITLE
W_SIGNAL syntax confusing Clang-format and Doxygen

### ISSUE THREAD

**Issue by rakhimov** [woboq/verdigris#12]
The trailing macro without a terminator is confusing clang-format (5.0) to indent the following lines.
Doxygen is confused:
```Found ';' while parsing initializer list! (doxygen could be confused by a macro call without semicolon)```

In its basic usage (without properties, default args),
the macro could be simplified to declare and define the signal function:
```cpp
#define W_SIGNAL0(name)              void name() W_SIGNAL(name)
#define W_SIGNAL1(name, type, param) void name(type param) W_SIGNAL(name, (type), param)
// so on w/ other arities ....
// or do the variadic version by interleaving the type and param lists?
```

This doesn't confuse clang, but doxygen cannot understand the implicit declaration.

**Comment by rakhimov** [comment]
Clang-format can be fixed w/ adding terminator semicolon after the macro:
```cpp
void mySignal(int myParam) W_SIGNAL(mySignal, int, myParam);
```

but now Doxygen thinks ``int`` and ``myParam`` are member data of the class missing docs.

**Comment by ogoffart** [comment]
It's not a bad idea to add W_SIGNALx.

For doxygen, maybe there is a way to tell it to ignore the macro?  Something like Adding something like `W_SIGNAL(...)=;`  in  doxygen's [PREDEFINED](https://www.stack.nl/~dimitri/doxygen/manual/config.html#cfg_predefined)

**Comment by rakhimov** [comment]
There are turns out to be two more Doxygen vars to set to YES:
``MACRO_EXPANSION`` and ``EXPAND_ONLY_PREDEF``
