### ISSUE TITLE
Static analysis tools and W_OBJECT macro

### ISSUE THREAD

**Issue by rakhimov** [woboq/verdigris#13]
This is probably not a major issue,
but it is interesting to know which tools start failing due to missing Q_OBJECT.
For example, ``lupdate`` is giving a warning.
Not sure about klazy or clazy.

**Comment by ogoffart** [comment]
What's the lupdate warning?

**Comment by rakhimov** [comment]
```Class '...' lacks Q_OBJECT macro```

**Comment by ogoffart** [comment]
We could teach lupdate to recognize the W_OBJECT macro

Otherwise , we need a workaround.  Since lupdate does not do the preprocessor, something like this should be added to every classes.

```
#if 0
    Q_OBJECT
#endif
```

Or 
```
#define IGNORE(...)
...
  IGNORE(Q_OBJECT)
```


maybe i could add a W_IGNORE macro in the wobjectdefs.h header

**Comment by rakhimov** [comment]
So far, this is a minor annoyance resulting in false positives at worst,
but there doesn't seem to be a tool that completely breaks when Q_Object is absent.
Reopen if you find one.
