### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by rakhimov** [woboq/verdigris#17]
It builds (kind of), ship it :)

**Comment by ogoffart** [comment]
Would be nice to try to have MSVC support before

**Comment by ogoffart** [comment]
What is missing for a release?

 - [ ] Add a `#define W_VERSION 0x010000`
 - [ ] Create a `v1.0` git tag
 - [ ] ???

**Comment by rakhimov** [comment]
Would be nice to start a changelog or release notes.

**Comment by ogoffart** [comment]
I'm about to create a v1.0 tag

**Comment by ogoffart** [comment]
Tag created.
