### ISSUE TITLE
Coverity scan

### ISSUE THREAD

**Issue by rakhimov** [woboq/verdigris#19]
One annoying thing about Qt moc is that generated code can have
compiler warnings or static analysis issues (false positives),
and you, as a user, can't do much about it but to ignore.
For example, [scram coverity report](https://scan.coverity.com/projects/2555) has most bugs in MOC code.

I hope Verdigris generated code won't have such issues.
Verdigris could setup continuous checks with Coverity and other static analysis tools (ex. clang scan-build).
An example configuration can be found on my fork:
https://github.com/rakhimov/verdigris/blob/coverity_scan/.travis.yml
I can't PR this config since it must be setup with the project owner tokens.
It still needs configuration to get it work with qmake.

**Comment by ogoffart** [comment]
So is there any warnings from coverity?

**Comment by rakhimov** [comment]
There configuration errors:
https://scan.coverity.com/projects/rakhimov-verdigris?tab=overview

Not sure where the problem is.

**Comment by ogoffart** [comment]
I am not authorized to access this page.

**Comment by rakhimov** [comment]
It basically says:
```
Last Build Status: Failed. Your build has failed due to the following reason. Please fix the error and upload the build again.
Error details: The build uploaded has been only partially compiled. We recommend at least 85% capture success to avoid false-positives during analysis. As per last few lines of cov-int/build-log.txt, the percentage of compilation units ready for analysis is 0% which is less than the expected 85%...more
```

You could register the project and try submitting user the config.

**Comment by ogoffart** [comment]
I am not going to register to coverity.
But I would fix issues if they are snesible.

**Comment by rakhimov** [comment]
Fair enough.
There are some warnings w/ -Wall as seen on Travis-CI.
At least it is now easier to ignore w/ specifying the verdigris headers as system.
