### ISSUE TITLE
Build fails with MSVC2015

### ISSUE THREAD

**Issue by jcelerier** [woboq/verdigris#2]
```
template<typename F, int N, typename ParamTypes, int... Flags>
constexpr MetaMethodInfo<F, N, sums(Flags...) | W_MethodType::Slot.value, ParamTypes>
makeMetaSlotInfo(F f, StaticStringArray<N> &name, const ParamTypes &paramTypes, W_MethodFlags<Flags>...)
{ return { f, {name}, paramTypes, {} }; }
```

I get a `syntax error: '...'` at ` sums(Flags...)`

**Comment by ogoffart** [comment]
A compiler that supports C++14 is required. That include GCC 5.1  or Clang 3.4.

Relaxed constexpr is required. But MSVC still does not fully support C++11 constexpr.

**Comment by ogoffart** [comment]
I just added a note in the README regarding the supported compilers

**Comment by jcelerier** [comment]
thanks, maybe also adding a 

    #if !defined(__cpp_constexpr) || __cpp_constexpr < 201304 
    #error Verdigris requires relaxed constexpr 
    #endif

would also help to pin-point the issue more clearly ? (because the poor compiler was suffocating under template errors...)

**Comment by ogoffart** [comment]
Yes, good idea.  Thanks for suggesting. Added in 00a4d7cec571759079c6afe025b9cb70645b4266
