### ISSUE TITLE
include vs. src

### ISSUE THREAD

**Issue by rakhimov** [woboq/verdigris#20]
The project is header only,
so shouldn't exported headers be in include dir instead of src?

**Comment by ogoffart** [comment]
I think  `src` is fine. Otherwise it would be empty.
What would be the reason for changing?

**Comment by rakhimov** [comment]
I think this is just a convention.
You could remove the src.
Initially, when I looked at the repo, my mind had an automatic wiring
that there's some implementation 'cpp' files to compile in src.
Plain include would have no surprises in this sense.

**Comment by ogoffart** [comment]
I'll keep it in src.
