### ISSUE TITLE
W_Access diagnostics

### ISSUE THREAD

**Issue by rakhimov** [woboq/verdigris#25]
I have been rewriting some QtTest-based code to use Verdigris
and stumbled on a subtle issue.

```cpp
class MyTest : public QObject {
  W_OBJECT(MyTest)

private /*slots*/:
  void testFoo() {}
  W_SLOT(testFoo)  // Oops, forgot W_Access::Private!
};
```

The mismatch of the access of a test slot
makes QtTest miss that test,
so ``testFoo`` is not going to run
because it is W_Access::Public by default/implicitly
but it should be W_Access::Private.

The issue is if a programmer makes this mistake (reasonable to assume),
there are no warnings at either compile time or run time.
In an ideal world, this code should either "do the right thing" or fail to compile.

Is this a solvable problem in the realm of Verdigris?

**Comment by rakhimov** [comment]
This is my quick sketch to find the function access automatically (requires C++17):

```cpp
struct Foo {
  void foo();
};

struct Bar {
protected:
  void foo();
};

struct Baz {
 private:
  void foo();
};

template <class T>
struct is_public {
 private:
  template <typename U, auto = &U::foo>
  static std::true_type test(int);

  template <typename>
  static std::false_type test(...);

 public:
  static constexpr const bool value
      = std::is_same_v<decltype(test<T>(0)), std::true_type>;
};

template <class T>
struct is_protected {
 private:
  struct D : T {
   private:
    template <typename U, auto = &U::foo>
    static std::true_type test(int);

    template <typename>
    static std::false_type test(...);

   public:
    static constexpr const bool value
        = std::is_same_v<decltype(test<D>(0)), std::true_type>;
  };

 public:
  static constexpr const bool value = !is_public<T>::value && D::value;
};

template <class T>
struct is_private {
  static constexpr const bool value
      = !is_public<T>::value && !is_protected<T>::value;
};

int main() {
  std::cerr << is_public<Foo>::value << std::endl;
  std::cerr << is_protected<Foo>::value << std::endl;
  std::cerr << is_private<Foo>::value << std::endl;

  std::cerr << is_public<Bar>::value << std::endl;
  std::cerr << is_protected<Bar>::value << std::endl;
  std::cerr << is_private<Bar>::value << std::endl;

  std::cerr << is_public<Baz>::value << std::endl;
  std::cerr << is_protected<Baz>::value << std::endl;
  std::cerr << is_private<Baz>::value << std::endl;
}
```

This is only for a single function without overloads.
I guess this can further be "macro-programmed" like Boost TTI does:
http://www.boost.org/doc/libs/1_66_0/libs/tti/doc/html/BOOST_TTI_TRAI_idp44570272.html

**Comment by ogoffart** [comment]
Thanks.

The problem with the code you have is that it does need the "foo" to appear as is in the code. So it needs to be within the macro. But since the W_SLOT macro is inside the class declaration, we get access to private and public member.

I initially did not do auto-detection of the access specifier because I was not sure how to do it.
But now I found a way and I am implementing it in commit 4f9b35b6bb278ea6a0bfc8724f98a4b87d0185cf

**Comment by ogoffart** [comment]
Ok, the build was fixed on MSVC after all.
Now the access is automatically detected
