### ISSUE TITLE
Properties are not accessible in QML

### ISSUE THREAD

**Issue by gillesfernandez** [woboq/verdigris#3]
When using the PropertyTutorial and exposing it to the QML, the properties are there in QML, but they are all 'undefined'.

Here is a small project that reproduces the issue : https://gitlab.com/Brethzel/VerdigrisTest/tree/master

Dump of the object in QML :
qml: objectName 
qml: prop1 undefined
qml: prop2 undefined
qml: prop3 undefined
qml: prop4 undefined
qml: map undefined
qml: objectNameChanged function() { [code] }
qml: valueChanged function() { [code] }

There's no problem for Q_INVOKABLE methods.

**Comment by ogoffart** [comment]
Fixed by commit 	2d72e62.   thanks for the report.
