### ISSUE TITLE
VS 2017 Update 7 compiler ICEs on verdigris code

### ISSUE THREAD

**Issue by mwu-tow** [woboq/verdigris#36]
I can successfully use verdigris with Visual Studio 2017 update 6. However, installing update 7 breaks it. The compiler throws an internal error: https://developercommunity.visualstudio.com/content/problem/221080/ice-in-constexpr-code-157-regression.html

It seems to be a regression in the compiler, I don't think that any action on the verdigris side is needed. I'm reporting this here just to let you know and warn other VS users.

As a workaround, it is possible to manually enable older compiler version for a given project as described in https://blogs.msdn.microsoft.com/vcblog/2017/11/15/side-by-side-minor-version-msvc-toolsets-in-visual-studio-2017/
The last toolset version that works for me is 14.13 (VS 2017.6).

**Comment by ogoffart** [comment]
I made a smaller testcase that reproduce the MSVC crash:

```
template<typename T>
struct MetaPropertyInfo {
    T t;

    constexpr auto setMember() const
    { return MetaPropertyInfo<T> {t}; }
};

struct XX  {
public:
    static constexpr auto w_PropertyState() {
        MetaPropertyInfo<std::nullptr_t> meta{ };
        return meta.setMember();
    }
};

int main() {
    constexpr auto doo = XX::w_PropertyState();
}
```

Interrestingly, if i replace std::nullptr_t with something else, it works.  So i'll do that

**Comment by jcelerier** [comment]
thanks !

**Comment by mwu-tow** [comment]
Thank you!
I have also updated the VS bugreport with the reduced repro.
