### ISSUE TITLE
W_PROPERTY does not seem to handle overloaded slots

### ISSUE THREAD

**Issue by jcelerier** [woboq/verdigris#41]
It can be witnessed by adding for instance a slot that takes an int in the PropertyTutorial example ; I tried to add qOverloads but couldn't make it work

**Comment by ogoffart** [comment]
qOverload should work, but should be applied to the variant without the READ / WRITE property.

```
W_PROPERTY(QString foo, qOverload<>(&Foobar::getter),  qOverload<QString>(&Foobar::setter))
```

**Comment by jcelerier** [comment]
thanks, that's what I was missing
