### ISSUE TITLE
Signals aren't connected if they are in a parent class across a DLL

### ISSUE THREAD

**Issue by jcelerier** [woboq/verdigris#42]
I have the following case : 

libfoo.so: 

    class Q_DECL_EXPORT Foo : public QObject {
      W_OBJECT(Foo)
      public:
      void pressed(QPointF) W_SIGNAL(pressed, pt);
    };

libbar.so: 

    class Bar : public Foo {
      W_OBJECT(Bar)
      public:
      // ...
    };

    connect(bar, &Bar::pressed, [] (QPointF) {});

As is, it does not work : the lambda does not get called. 
It does get called if I either statically link, or re-add the signal explicitely in `Bar`'s definition.

**Comment by ogoffart** [comment]
What compiler are you using?

can you try to do 

```
Q_DECL_EXPORT void pressed(QPointF) W_SIGNAL(pressed, pt);
```

My guess is that because the signal is inline, it is not exported.
Also try things such as `__attribute__ ((noinline))`, or `-fno-inline`


But even if the function is not exported, it should still have the same address. So that'd be a compiler bug.

The question is how can we work around it...

**Comment by jcelerier** [comment]
> What compiler are you using?

GCC 8. Just tried __attribute__ ((noinline)) but it did not change. Gonna try with clang 6 tomorrow

**Comment by jcelerier** [comment]
looking about around this, and from my (fairly limited) understanding of the meta-object system, I'm wondering if the problem isn't rather on the side of what happens in W_OBJECT_IMPL, or with the constexpr variables after the signal implementation in W_SIGNAL : for instance even if I explicitely create a connection in libfoo.so in order to ODR-usr everything possible, I still don't get it from my other DLL, and I get error messages such as 

     QObject::connect: signal not found in Bar

**Comment by ogoffart** [comment]
I cannot reproduce the problem locally.

I put your code in lib.cpp and app.cpp, and did

```
g++ -shared -o libfoo.so lib.cpp -I /usr/include/qt  -I ~/woboq/verdigris/src/ -fPIC -fvisibility=hidden
g++  -lfoo app.cpp -I /usr/include/qt  -I ~/woboq/verdigris/src/ -fPIC -lQt5Core -L. -fvisibility=hidden   
```

But that worked just fine.

**Comment by jcelerier** [comment]
here's a repro (tested on linux / g++ but I had the same problem on macos with clang), build with `make all`.

[bug-connect.zip](https://github.com/woboq/verdigris/files/2144806/bug-connect.zip)

**Comment by ogoffart** [comment]
The problem is with `-fvisibility-inlines-hidden`  because then the signal, which are inline with verdigris, are not exported. So they do not have the same address accros libraries. The solution: explicitly exporting the signal.

```c++
// lib1.h
#pragma once
#include <QtCore/QObject>
#include <wobjectdefs.h>

class Q_DECL_EXPORT Foo : public QObject {
  W_OBJECT(Foo)
  public:
    ~Foo();
    /*Q_DECL_EXPORT*/ void  pressed(int x, int y) W_SIGNAL(pressed, x, y);
};

// lib1.cpp
#include "lib1.hpp"
#include <wobjectimpl.h>
W_OBJECT_IMPL(Foo)

// main.cpp
#include "lib1.hpp"
#include <QtCore/QDebug>
int main(int argc, char** argv)
{
    Foo f;
    QObject::connect(&f, &Foo::pressed, [] (int x, int y) { qDebug() << x << y; });
    f.pressed(1, 23);
}

/* -- Build instructions
g++ -g -shared -fvisibility=hidden -fvisibility-inlines-hidden lib1.cpp -o libfoo.so -lQt5Core -I/usr/include/qt  -I. -fPIC
g++ -g -fvisibility=hidden -fvisibility-inlines-hidden main.cpp -lQt5Core -I/usr/include/qt  -I. -fPIC -ldl -lfoo -L.
LD_LIBRARY_PATH=. ./a.out
*/
```

Uncommenting the Q_DECL_EXPORT seems to fix the problem, as it explicitly mark the funciton as exported, despite being inline

I guess this should be documented.

I can't think of another way to workaround the problem.

**Comment by ogoffart** [comment]
I added a note in the documentation with commit bb45ec1

**Comment by jcelerier** [comment]
weird, I always believed that marking a class / struct as EXPORT would implicitely mark all its members, both inline and non-inline as EXPORT. Going to ask on some compiler IRC channels.

**Comment by jcelerier** [comment]
since life was apparently too easy, MSVC has the opposite behaviour : marking the inline functions as EXPORT plainly does not compile, and they are exported by default.

https://godbolt.org/g/S7iV5P

**Comment by jcelerier** [comment]
So, after some exploration, here are my conclusions : 

given the following code : 

```C++
#include <vector>
#include <cstdlib>
#ifdef _MSC_VER
 #define EXPORT     __declspec(dllexport)
#else
 #define EXPORT     __attribute__((visibility("default")))
#endif

struct EXPORT foo
{
    void f() { }
    void g();

    #if !defined(_MSC_VER)
    EXPORT
    #endif
    // re-exporting does not compile on msvc
    void h() { }

};

// Always exported since foo is marked EXPORT
void foo::g()
{
}

/*
EXPORT
void simple_use()
{
    // At O1 this creates the symbols on clang, not on GCC.
    // At O3 this does not create the symbols on either.
    foo{}.f();
    foo{}.h();
}
*/

/*
void do_stuff(void (foo::* ptr)());

EXPORT
void odr_use()
{
    // ODR-use of f and h allows them to be in the binary in all cases
    do_stuff(&foo::f);
    do_stuff(&foo::h);
}
*/
```

we have the following behaviour : 

| Tables        | No use    | Simple use  | ODR use 
| ------------- |:---------------:| ---------------:| ---------------:|
| g++ -O0    |     only g     | t f, T g, W h | t f, T g, W h |
| g++ -O1    |     only g     | only g          | t f, T g, W h |
| g++ -O2    |     only g     | only g          | t f, T g, W h |
| ------------- |:---------------:| ---------------:| ---------------:|
| clang -O0 |     only g     | t f, T g, W h | t f, T g, W h |
| clang -O1 |     only g     | t f, T g, W h | t f, T g, W h |
| clang -O2 |     only g     | only g          | t f, T g, W h |
| ------------- |:---------------:| ---------------:| ---------------:|
| MSVC /O0 | everything |    -      |    -    |
| MSVC /Ox | everything |    -      |    -    |

**Comment by ogoffart** [comment]
Then you need to define  FOO_EXPORT_SIGNAL  which expand to FOO_EXPORT but to nothing for MSVC

**Comment by jcelerier** [comment]
considering that on GCC and Clang, function attributes can also live after the function declaration, wouldn't it be possible to make the export part of the W_SIGNAL macro in this case ? 

e.g. this works:  

```C++
#ifdef _MSC_VER
 #define EXPORT     __declspec(dllexport)
 #define SIGNAL_EXPORT
#else
 #define EXPORT     __attribute__((visibility("default")))
 #define SIGNAL_EXPORT __attribute__((visibility("default")))
#endif

struct EXPORT foo
{
    void f() { }
    void g();

    void h() SIGNAL_EXPORT { }
};
```

**Comment by jcelerier** [comment]
though maybe some people won't want automatic signal export - I'll just make my own binding macro.
