### ISSUE TITLE
MSVC release 15.7.6 breaks verdigris at /std:c++latest or /std:c++17

### ISSUE THREAD

**Issue by jcelerier** [woboq/verdigris#43]
Adding 

    QMAKE_CXXFLAGS += /std:c++latest

or

    QMAKE_CXXFLAGS += /std:c++17

in verdigris.pri does it - there's not a lot which compiles anymore. 

I'm on visual studio 15.7.6. cl.exe 19.14.26433

**Comment by jcelerier** [comment]
The first issue I encounter can resolve to this : 


    // ok:
    void f(int x) { }
    using t1 = QtPrivate::FunctionPointer<decltype(&f)>::Arguments;

    // fail: 
    void f(int x) noexcept { }
    using t1 = QtPrivate::FunctionPointer<decltype(&f)>::Arguments;

**Comment by ogoffart** [comment]
Right, this is a Qt issue. In C++17, noexcept is part of the function signature, which means  that noexcept signal and slot were broken. Qt fixed it if __cpp_noexcept_function_type is defined to the right value.  But MSVC don't define that.
You can't have noexcept signal and slot in that case. This is not a verdigris issue (altough verdigris test for it)

What exactly is broken? Is it just verdigris tests, or your actual program?

You should could try to define `__cpp_noexcept_function_type` to `201510`

Note that if Qt decide to fix this using some special macro, I would also need to update verdigris, as we also use `__cpp_noexcept_function_type` in `wobjectdefs.h`

**Comment by jcelerier** [comment]
> What exactly is broken? Is it just verdigris tests, or your actual program?

well, it was my program, then I ran the verdigris tests and noticed that they were broken too. 
I solved the error on my side by defining a MSVC_NOEXCEPT macro.
However, while it solved the build of my program, this is only one issue among many that cropped up when running the verdigris tests.

In any case, I'll report it to qt.

**Comment by ogoffart** [comment]
@jcelerier what's the status of this? Did you report the problem to Qt? If yes, what's the bug number?

**Comment by jcelerier** [comment]
here it is : https://bugreports.qt.io/browse/QTBUG-69842 ; I had forgotten about it but anyways if it's not handled in Qt I might as well close this one ?

**Comment by ogoffart** [comment]
Thanks.
Since Qt will not fix this issue, that also means there is nothing to do in verdigris. So I'll close this issue.

If Qt would work around the problem, verdigris should apply the same work around.
