### ISSUE TITLE
Qt Translations not shown when W_OBJECT_IMPL in namespace

### ISSUE THREAD

**Issue by jessicaWS** [woboq/verdigris#45]
Translations of a class in a namespace are not shown in the application, if the macro `W_OBJECT_IMPL` is also used inside this namespace.
Example:
 ```
// test.hpp
#include<QObject>
#include <verdigris/wobjectimpl.hpp>
namespace test{
    class Test : public QObject
    {
        W_OBJECT(Test)
     public:
        Test();
    };
}
```
```
// test.cpp
#include<test.hpp>
namespace test{
    W_OBJECT_IMPL(Test) 
    Test::Test()
    {
        std::cout << tr("Text").toStdString();
    }

}
```
Using lupdate on an `QApplication` including this file, the Translation with `tr` would be shown in the `.ts` file. When inserting the translation in the `.ts` file and running the application, the text is not translated, when the `W_OBJECT_IMPL` is used inside the namespace.
When the `.cpp` file above would have the macro outside the namespace (like below), the translation would be shown when running an application that uses this class.
```
// test.cpp
#include<test.hpp>
W_OBJECT_IMPL(test::Test) 
namespace test{
    Test::Test()
    {
        std::cout << tr("Text").toStdString();
    }

}
```

It would be either helpful to change the macro, so that is can't be used inside a namespace or that translations are still shown even when this is done.

**Comment by ogoffart** [comment]
Thanks for the bug report.

Indeed, QMetaObject::className contains the "test::" when parsed with moc.  Therefore, it must be there in W_OBJECT_IMPL.
So you should always do  `W_OBJECT_IMPL(test::Test)`
I updated the documentation to reflect that.
But you can put it like that in the namespace, it should work.

Some magic could be done with W_NAMESPACE, I don't konw if it is worth it though.
