### ISSUE TITLE
Build fails with latest MSVC (15.9)

### ISSUE THREAD

**Issue by jcelerier** [woboq/verdigris#46]
because of course ...

there is an immense amount of errors that appears simply by running the verdigris unit tests

**Comment by jcelerier** [comment]
I've sent an issue ticket to MS asking them to put the lib in their test suite, I'll keep you posted on it

**Comment by ogoffart** [comment]
Could you paste example of these errors?

**Comment by jcelerier** [comment]
hmm, they're in french if it's not a problem, I don't know how I can ask cl.exe to output in english : 

https://gist.github.com/jcelerier/e2ab319a4fa1d2343eb614827ba8f7d4

**Comment by jcelerier** [comment]
Still fails with VS 16. ("Visual Studio 2019") :(

**Comment by ogoffart** [comment]
I have personally not tested MSVC 2019 yet.
If you manage to find a workaround, i'd be happy to apply it.
