### ISSUE TITLE
Overflow when using clang-cl

### ISSUE THREAD

**Issue by grefab** [woboq/verdigris#47]
Any reason these particular values for the enum are chosen?

https://github.com/woboq/verdigris/blob/511ed16f79eb3c0f0ef9a16ab900dc32eb39f23f/src/wobjectimpl.h#L49

Because when I try to build a Verdigris/Qt-app with clang-cl (works fine with clang7/Linux oder MSVC/Windows) I get the following error:

`error: non-type template argument evaluates to -2147483648, which cannot be narrowed to type 'uint' (aka 'unsigned int')`
Pointing at `IsUnresolvedType`. I changed the values to

`enum { IsUnresolvedType = 0x00800000, IsUnresolvedNotifySignal = 0x00700000 };`

and now it builds. Anything I should consider?

**Comment by ogoffart** [comment]
These need to match the constant that Qt expects.
See https://code.woboq.org/qt5/qtbase/src/corelib/kernel/qmetaobject_p.h.html#MetaDataFlags

So i'd be surprise if the tests still pass after your change.

I just committed 00d846a which might fix the warning.

If it does not, maybe some explicit casting in IntermediateState::addTypeString  might help.
