### ISSUE TITLE
Constexpr API

### ISSUE THREAD

**Issue by arBmind** [woboq/verdigris#50]
The current implementations is a big relieve. But API relies heavily on Macros.

We are generating Properties and Signals based on C++ constructs (eg. tuples).
To do this we resolved the macros with the code that is generated. Also this works well, it's feels very ugly.
The generated code is tailored towards the macros.

From my perspective it would be very beneficial to create a second API that is more tailored towards a C++ API.

Examples:
```cpp
    friend constexpr auto w_PropertyState(w_internal::w_number<1> w_counter, This** w_this) {
        auto tree = w_PropertyState(w_counter.prev(), w_this);
        auto mapped = /* … */;
        return w_internal::binary::tree_append(tree, mapped);
    }
```
It would be easy to add a `constexpr auto w_CustomProperties()` that returns an array of PropertyInfos.
This would also allow Verdigris to perform some internal processing - like the hashing.

What do you think? Any chances a PR for this would be accepted?

**Comment by ogoffart** [comment]
Can you please elaborate on the use case?
you want to add properties that you create yourself with some other constexpr programming, without using the W_PROPERTY macro?
That sounds like a good idea.

> Any chances a PR for this would be accepted?

Sure

**Comment by arBmind** [comment]
> you want to add properties that you create yourself with some other constexpr programming, without using the W_PROPERTY macro?
Excactly!

Basically, we have a compile time schema that has all the details about the data. It's stored and managed in repositories that are not aware of Qt.
For the QtQuick based Gui, we need valid QObjects and ItemModels.
As I said, this all works fine, but is quite ugly right now.

> > Any chances a PR for this would be accepted?
>
> Sure
Sounds great!

Be aware, that I have no fully conclusive plan right now.
In order to publish a compile time API, we need:
* some form of static strings - to transport names
* a way to create MetaPropertyInfo, MetaMethodInfo
* a way to inject those into the MetaObject creation

I will try to sketch a PR soon…
