### ISSUE TITLE
Verdigris works amazingly well but did not replace moc in Qt6

### ISSUE THREAD

**Issue by fiesh** [woboq/verdigris#80]
Just joking, but only half... we've been using verdigris for a couple years now and entirely replaced `moc`.  It works so well, with QML and everything, and allows templated `QObjects` which was key to having `QFuture`s in a way they can be used without omfg-hacks.

So why did it not make it into Qt6? :-(  Such a shame!

Such a great project.

**Comment by ogoffart** [comment]
The Qt community is happy with `moc` which serves its purpose. The few amount of people who wants to use templated QObject can either use verdigris, or not do it.

Now, the verdigris bug tracker is not really a good location to ask such a question :-) 
The Qt bug tracker would be a better place to do this kind of wishes.
