### ISSUE TITLE
Add Support for noexcept in C++17

### ISSUE THREAD

**Issue by mmha** [woboq/verdigris#9]
Starting with C++17 `noexcept`  is part of the type system. This breaks `W_PROPERTY` with member functions that are marked as `noexcept(true)`. The following example compiles in C++14 mode, but not in C++17:

```
class SomeClass  : public QObject {
    W_OBJECT(SomeClass)
    int x_;
public:
    int x() const noexcept { return x_; }
    W_PROPERTY(int, prop1 READ x)
};
```

**Comment by ogoffart** [comment]
Fixed in commit 9f2f062,  thanks for reporting
